### PR TITLE
Fix the Quickstart tutorial and make the docs refer to this repo instead of a fork

### PR DESCRIPTION
**Pull request by dave7895**
This *should* fix the erroring tests, as I removed the reference to a local DLPipelines or at least change the location of/reason for the error.

### CODE REVIEW

**Comment by lorenzoh** [comment]
Thanks for the contribution! Could you remove the change to the `validbsfactor` parameter? That needs a different fix which I'll do. Afterwards you can merge the main branch into this PR and it should work.

**Comment by dave7895** [comment]
I hope this satisfies your request.

**Comment by lorenzoh** [comment]
I've gone ahead and removed the `encode` method as it was fixed with the release of DLPipelines.jl v0.2.0.

**Comment by dave7895** [comment]
So revert everything except the docs fix?

**Comment by lorenzoh** [comment]
Should be the case now, I'll merge once the checks have run through 👍

**Comment by dave7895** [comment]
I messed up the commit history. Should I clean it up and force push again?

**Comment by lorenzoh** [comment]
You don't need to, I'll squash the commits down into one when I merge

**Pull request merged**
