### PR TITLE
Add food-101 recipe

### PR DESCRIPTION
**Pull request by Chandu-4444**
I've added `food-101` to the RECIPES

Ref: #153

### CODE REVIEW

**Comment by lorenzoh** [comment]
Have you tested loading this into a data container and can you check that `checkblock(getobs(data, 1), blocks)` is `true`?

**Comment by Chandu-4444** [comment]
Oh, I forgot about tests. I'll check and will update the tests.

**Comment by lorenzoh** [comment]
You don't need to write test cases for this, just test it manually. Unfortunately, we can't test every dataset recipe all the time since then CI would have to download every dataset (and just this one is a few GB I think)

**Comment by Chandu-4444** [comment]
Okay, I'll test it manually and will update it here then 👍

**Comment by Chandu-4444** [comment]
> Have you tested loading this into a data container and can you check that `checkblock(getobs(data, 1), blocks)` is `true`?

Yeah, it returned true.

**Comment by lorenzoh** [comment]
Thanks for checking!

**Pull request merged**
